# config.ini

[Video]
width=1920
height=1080
fps=60
bitrate=600000

[Audio]
samplerate=48000
a_bitrate=192000

[stream]
rtmpUrl=rtmp://live.twitch.tv/app/YOUR_STREAM_KEY

[Encoder]
preset=veryfast
tune=zerolatency